# 1. Воровство w2v 

In [1]:
import gensim 
print(gensim.__version__)

3.8.0


In [2]:
w2v_model = gensim.models.KeyedVectors.load_word2vec_format("184/model.bin", binary=True)

In [6]:
w2v_model.get_vector('путин_NOUN').shape

(300,)

In [13]:
w2v_model.most_similar('россия_PROPN')

[('рф_PROPN', 0.5658383965492249),
 ('рф::россия_PROPN', 0.4791482090950012),
 ('песковарищ_NOUN', 0.46943381428718567),
 ('устроитьтеррористическать_ADJ', 0.46034306287765503),
 ('амарин_PROPN', 0.45849233865737915),
 ('силуановадратный_ADJ', 0.45033103227615356),
 ('гончаровадратный_ADJ', 0.4423750638961792),
 ('iraqinews_PROPN', 0.4374409317970276),
 ('приговоренута_NOUN', 0.4364970922470093),
 ('премьерминистр_NOUN', 0.4326789379119873)]

In [14]:
w2v_model.most_similar(positive=['трамп_PROPN','россия_PROPN'], negative=['сша_PROPN'])

[('ильковский_ADJ', 0.35678017139434814),
 ('дональд_PROPN', 0.353410005569458),
 ('асcанж_PROPN', 0.35311537981033325),
 ('n-tv.сообщаться_VERB', 0.3511354923248291),
 ('асcанж_NOUN', 0.34586143493652344),
 ('интерфвкс_PROPN', 0.34339189529418945),
 ('щеголева_NOUN', 0.3423219621181488),
 ('дональд::трамп_PROPN', 0.34094905853271484),
 ('липко.директор_PROPN', 0.33982157707214355),
 ('функционаливать_NOUN', 0.3345367908477783)]

In [15]:
vocab = w2v_model.vocab
len(vocab)

249318

In [19]:
import numpy as np
from tqdm import tqdm  #tqdm_notebook

uniq_words = {"#PAD#": 0, "#UNK#": 1}

s = len(vocab) + 2
d = 300

embedings = np.zeros((s, d))

for i, word in tqdm(enumerate(vocab)):
    uniq_words[word] = (i + 2)
    embedings[i + 2] = w2v_model.get_vector(word)

249318it [00:01, 135183.43it/s]


In [20]:
embedings.shape

(249320, 300)

In [25]:
embedings[uniq_words['путин_NOUN']].shape

(300,)

In [26]:
np.save('embeding.npy', embedings)

In [28]:
import pickle

with open('vocab.pickle', 'wb') as f:
    pickle.dump(uniq_words, f)

# 2. Данные

In [110]:
data = [
    {'category': 'В мире',
 'date': '2018-12-31',
 'day': '31',
 'href': '/20181231/1548961410.html',
 'image': 'https://cdn25.img.ria.ru/images/153303/06/1533030626_0:247:3501:2216_1036x0_80_0_0_291c92f1d31f7b2a613588e6a96164cb.jpg',
 'keywords': 'биньямин нетаньяху, израиль, в мире',
 'month': '12',
 'shows': '728',
 'snippet': 'Премьер-министр Израиля Биньямин Нетаньяху не намерен уходить в отставку в случае предъявления ему обвинений в коррупции, сообщает израильский телеканал i24... РИА Новости, 31.12.2018',
 'tags': 'Биньямин Нетаньяху, Израиль, В мире',
 'text': 'МОСКВА, 31 дек - РИА Новости. Премьер-министр Израиля Биньямин Нетаньяху не намерен уходить в отставку в случае предъявления ему обвинений в коррупции, сообщает израильский телеканал i24 News. В начале декабря полиция рекомендовала генпрокуратуре предъявить обвинения в коррупции Нетаньяху и его супруге Саре по итогам расследования дела об их отношениях с руководством крупнейшей в стране телекоммуникационной компании "Безек". Как отмечает телеканал, в случае предъявления обвинений глава правительства законодательно обязан уйти в отставку только в случае, если будет исчерпан его апелляционный ресурс. Нетаньяху проходит подозреваемым еще по двум другим уголовным делам, которые полиция уже передала в прокуратуру с рекомендацией предъявить ему те же обвинения — во взяточничестве, мошенничестве и злоупотреблении доверием. Во всех случаях премьер настаивает на своей невиновности, выражает уверенность, что расследования против него завершатся ничем, и обещает еще многие годы руководить страной.',
 'time': '31 декабря 2018, 23:52',
 'title': 'Нетаньяху не собирается в отставку в случае предъявления обвинений ',
 'year': '2018'},
    
       {'category': 'В мире',
 'date': '2018-12-31',
 'day': '31',
 'href': '/20181231/1548961410.html',
 'image': 'https://cdn25.img.ria.ru/images/153303/06/1533030626_0:247:3501:2216_1036x0_80_0_0_291c92f1d31f7b2a613588e6a96164cb.jpg',
 'keywords': 'биньямин нетаньяху, израиль, в мире',
 'month': '12',
 'shows': '728',
 'snippet': 'Премьер-министр Израиля Биньямин Нетаньяху не намерен уходить в отставку в случае предъявления ему обвинений в коррупции, сообщает израильский телеканал i24... РИА Новости, 31.12.2018',
 'tags': 'Биньямин Нетаньяху, Израиль, В мире',
 'text': 'уге Саре по итогам расследования дела об их отношениях с руководством крупнейшей в стране телекоммуникационной компании "Безек". Как отмечает телеканал, в случае предъявления обвинений глава правительства законодательно обязан уйти в отставку только в случае, если будет исчерпан его апелляционный ресурс. Нетаньяху проходит подозреваемым еще по двум другим уголовным делам, которые полиция уже передала в прокуратуру с рекомендацией предъявить ему те же обвинения — во взяточничестве, мошенничестве и злоупотреблении доверием. Во всех случаях премьер настаивает на своей невиновности, выражает уверенность, что расследования против него завершатся ничем, и обещает еще многие годы руководить страной.',
 'time': '31 декабря 2018, 23:52',
 'title': 'Нетаньяху не собирается',
 'year': '2018'},
    
       {'category': 'В мире',
 'date': '2018-12-31',
 'day': '31',
 'href': '/20181231/1548961410.html',
 'image': 'https://cdn25.img.ria.ru/images/153303/06/1533030626_0:247:3501:2216_1036x0_80_0_0_291c92f1d31f7b2a613588e6a96164cb.jpg',
 'keywords': 'биньямин нетаньяху, израиль, в мире',
 'month': '12',
 'shows': '728',
 'snippet': 'Премьер-министр Израиля Биньямин Нетаньяху не намерен уходить в отставку в случае предъявления ему обвинений в коррупции, сообщает израильский телеканал i24... РИА Новости, 31.12.2018',
 'tags': 'Биньямин Нетаньяху, Израиль, В мире',
 'text': 'зраильский телеканал i24 News. В начале декабря полиция рекомендовала генпрокуратуре предъявить обвинения в коррупции Нетаньяху и его супруге Саре по итогам расследования дела об их отношениях с руководством крупнейшей в стране телекоммуникационной компании "Безек". Как отмечает телеканал, в случае предъявления обвинений глава правительства законодательно обязан уйти в отставку только в случае, если будет исчерпан его апелляционный ресурс. Нетаньяху проходит подозреваемым еще по двум другим уголовным делам, которые полиция уже передала в прокуратуру с рекомендацией предъявить ему те же обвинения — во взяточничестве, мошенничестве и злоупотреблении доверием. Во всех случаях премьер настаивает на своей невиновности, выражает уверенность, что расследования против него завершатся ничем, и обещает еще многие годы руководить страной.',
 'time': '31 декабря 2018, 23:52',
 'title': ' обвинений ',
 'year': '2018'}]

In [111]:
data[0]['title']

'Нетаньяху не собирается в отставку в случае предъявления обвинений '

In [51]:
from pymorphy2 import MorphAnalyzer
m = MorphAnalyzer()

m.parse('собираться')[0].tag.POS

'INFN'

In [114]:
from nltk.tokenize import word_tokenize
import re

def prepare_text(text, limit):
    tokens = word_tokenize(re.sub('[^a-яa-z ]', '', text.lower()))
    tk = []
    for word in tokens:
        try:
            wd = word + '_' + m.parse(word)[0].tag.POS
        except:
            wd = "#UNK#"
        tk.append(wd)
  
    clean_tokens = [uniq_words[word] if word in uniq_words else uniq_words["#UNK#"] for word in tk]
    
    if len(clean_tokens) >= limit:
        return clean_tokens[:limit]
    else:
        return clean_tokens + [0]*(limit - len(clean_tokens))

In [229]:
text_ex = np.array([prepare_text(item['text'], 100) for item in data])  # квантиль 0.99 это 100
title_ex = np.array([prepare_text(item['title'], 10) for item in data]) # квантиль 0.99 это 10
y_ex = np.array([[1,0],[1,0],[1,0]])

In [230]:
text_ex.shape

(3, 100)

In [231]:
text_ex

array([[ 27706,      1,  18928, 121003, 119611,      1,      1,  50733,
             1,      1,      1,      1, 115049,      1,      1,      1,
             1,      1,      1,      1,      1,      1,    390,      1,
             1,      1, 151045,  46356,    125,      1,      1,      1,
             1,      1,      1,  50733,      1,      1,      1,      1,
             1,      1,  54053,  11403,      1,      1,      1,      1,
             1,      1,      1,      1,      1,  57642,      1,      1,
             1,    390,      1,      1,      1,      1,     29,   9848,
             1,      1,      1,      1, 115049,      1,      1,      1,
             1,      1,      1,      1,      1,   1283,  50733,      1,
             1,      1,      1,      1,      1,      1,      1,      1,
           125,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1],
       [     1,      1,      1,      1,  54053,  11403,      1,      1,
             1,      1,

# 3. Архитектура

In [232]:
import tensorflow as tf 
keras, L = tf.keras, tf.keras.layers

from tensorflow.keras import Model

In [233]:
embedings.shape

(249320, 300)

In [234]:
word_embedings = tf.Variable(embedings, name='embedings', trainable=False, dtype=tf.float32)
word_embedings[20][:10]

<tf.Tensor: id=2034, shape=(10,), dtype=float32, numpy=
array([-0.01659287,  0.1365179 ,  0.2862364 ,  0.06131566, -0.48168   ,
        0.46524763, -0.04386752, -0.29350498, -0.04113811, -0.17267391],
      dtype=float32)>

In [235]:
class ItemEncoder(Model):
    def __init__(self):
        super(ItemEncoder, self).__init__()  # техническая штука ООП 
        
        self.word_embedings = word_embedings
        self.conv_layer1 = L.Conv1D(16, kernel_size=2, activation=tf.nn.relu)
        self.conv_layer2 = L.Conv1D(16, kernel_size=3, activation=tf.nn.relu)
        self.fc_layer = L.Dense(10, activation=tf.nn.relu)
        
    def call(self, x):
        
        # подставляет эмбединги вместо слов 
        item_emb = tf.nn.embedding_lookup(self.word_embedings, x)
        
        # свертка для биграммы 
        emb1 = self.conv_layer1(item_emb)
        emb1 = tf.reduce_mean(emb1, axis=2)
        
        emb2 = self.conv_layer2(item_emb)
        emb2 = tf.reduce_mean(emb2, axis=2)
        
        emb3 = tf.reduce_mean(item_emb, axis=1)
        
        emb = tf.concat([emb1, emb2, emb3], axis=1)
        emb = self.fc_layer(emb)
        return emb

In [236]:
class TextEncoder(Model):
    def __init__(self):
        super(TextEncoder, self).__init__()  # техническая штука ООП 
        
        self.encoder1 = ItemEncoder()
        self.encoder2 = ItemEncoder()
        self.fc_layer = L.Dense(2, activation=tf.nn.softmax)
        
    def call(self, title, text):
        
        text_emb = self.encoder1(text)
        title_emb = self.encoder2(title)
        
        emb = tf.concat([text_emb, title_emb], axis=1)
        emb = self.fc_layer(emb)
        
        return emb

In [237]:
encoder = TextEncoder()

In [238]:
encoder(title_ex, text_ex)

<tf.Tensor: id=2269, shape=(3, 2), dtype=float32, numpy=
array([[0.58631694, 0.4136831 ],
       [0.53310627, 0.46689376],
       [0.54703295, 0.45296708]], dtype=float32)>

In [239]:
len(encoder.trainable_variables)

14

In [240]:
def logloss(p, y):
    return tf.reduce_mean(-1*tf.reduce_sum(y*tf.math.log(p), axis=1), axis=0)

p = np.array([[0.5,0.5],[0.7,0.3]])
y = np.array([[1.,0.],[0.,1.]])

logloss(p, y)

<tf.Tensor: id=2279, shape=(), dtype=float64, numpy=0.9485599924429406>

In [241]:
opt = tf.optimizers.SGD(learning_rate=0.001)

In [242]:
def model_train(title_ex, text_ex, y_ex):
    
    with tf.GradientTape() as g:
        pred = encoder(title_ex, text_ex)
        loss = logloss(pred, y_ex)
        
    gradients = g.gradient(loss, encoder.trainable_variables)
    opt.apply_gradients(zip(gradients, encoder.trainable_variables))

In [244]:
model_train(title_ex, text_ex, y_ex)

In [248]:
epochs = 5

for i in range(epochs):
    
    # генератор батчей 
    
    # обучение делаем на батчах 
    model_train(title_ex, text_ex, y_ex)
    
    # качество смотрим на валидации
    y_pred = encoder(title_ex, text_ex)
    print(f"Эпоха {i}, качество {logloss(y_pred, y_ex).numpy()}")

Эпоха 0, качество 0.5679793357849121
Эпоха 1, качество 0.5667052268981934
Эпоха 2, качество 0.5654342770576477
Эпоха 3, качество 0.5641661286354065
Эпоха 4, качество 0.5629040598869324
